name: cifar10_imb001_stage1_mixup/SGD_STEP/lr_0.01
print_freq: 40
workers: 4
log_dir: 'logs'
model_dir: 'ckps'
binary: True

# dataset & model setting
dataset: 'cifar10'
data_path: './data/cifar10'
num_classes: 10
imb_factor: 0.01
resume: ''
head_class_idx:
  - 0
  - 36
med_class_idx:
  - 36
  - 71
tail_class_idx:
  - 71
  - 100


# distributed training
deterministic: False
distributed: False
gpu: null
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False


# Train
mode: 'stage1'
lr: 0.01
batch_size: 128
optimizer: 'SGD'
scheduler: 'step'
weight_decay: 2e-4
num_epochs: 200
momentum: 0.9
cos: False
mixup: False
alpha: 0.0




